export const ROUTES = {
    APP: '/app',
    AUTH: '/auth',
    HOMEPAGE_ROUTE: '/',
    CREATEMERCHANTPAGE_ROUTE: '/create-merchant',
    LOGIN_ROUTE: '/login',
    VIEWMERCHANTSPAGE_ROUTE: '/view-merchants',
    UPDATEMERCHANTACCOUNTPAGE_ROUTE: '/update-merchant-account',
    VIEWMERCHANTACCOUNTPAGE_ROUTE: '/view-merchant-account',
    VIEWINDIVIDUALPAGE_ROUTE: '/view-individual',
    UPDATEINDIVIDUALPAGE_ROUTE: '/update-individual',
    VERIFYINDIVIDUALPAGE_ROUTE: '/verify-individual',
    PAYROLLPAGE_ROUTE: '/transfers',
    PAYROLLDETAILSPAGE_ROUTE: '/payroll-details',
    RECIPIENTDETAILSPAGE_ROUTE: '/recipient-details',
    RESETPASSWORDPAGE_ROUTE: '/reset-password',
    SETTINGSPAGE_ROUTE: '/settings',
    SUPPORTPAGE_ROUTE: '/support',
    ACCOUNTPAGE_ROUTE: '/account',
    DEPOSITPAGE_ROUTE: '/deposit',
    CREATESUBACCOUNTPAGE_ROUTE: '/create-sub-account',
    VIEWSUBACCOUNTSPAGE_ROUTE: '/view-sub-accounts',
    MERCHANTSTATEMENTPAGE_ROUTE: '/view-merchant-statement',
    PAYMENTLINKPAGE_ROUTE: '/merchant-payment-link',
    SUBMERCHANTTRANSACTIONSPAGE_ROUTE: '/sub-merchant-transactions'
}